# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] || 'gyandip' %>
  password: <%= ENV["POSTGRES_PASSWORD"] || 'gyandip' %>

development:
  <<: *default
  database: ruby-test-development

test:
  <<: *default
  database: ruby-test-test

production:
  <<: *default
  database: ruby-test-production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>

